# Dell XPS 14"
# Originally generated by nixos-generate-config.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
      ../hosts/configuration.nix
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "xe" ];  # Early modesetting for Intel Arc GPU
  boot.kernelModules = [ "kvm-intel" "hid_apple" ];
  boot.extraModulePackages = [ ];
  boot.extraModprobeConfig = ''
    options hid_apple swap_fn_leftctrl=1
  '';

  # Disable Panel Self Refresh and Panel Replay — known to cause input lag
  # and stale frame updates on Intel Xe GPUs (Panther Lake / Arc).
  boot.kernelParams = [
    "xe.enable_psr=0"
    "xe.enable_panel_replay=0"
  ];
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
  };

  networking.networkmanager = {
    enable = true;
    wifi.powersave = false;
  };

  fileSystems."/" =
    { device = "/dev/mapper/cryptroot";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/9b073aa2-9766-450e-b3f0-efcaf97075c8";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E631-1227";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Intel Panther Lake (Arc B390) GPU acceleration
  hardware.graphics.extraPackages = with pkgs; [
    intel-media-driver  # VA-API hardware video decode/encode
    vpl-gpu-rt          # Intel oneVPL GPU runtime
  ];

  nixpkgs.overlays = [
    (import ../overlays/google-chrome.nix)
  ];

  services.logind.lidSwitch = "suspend";

  services.hardware.bolt.enable = true;

  services.tlp = {
    enable = true;
    settings = {
      CPU_SCALING_GOVERNOR_ON_AC = "performance";
      CPU_SCALING_GOVERNOR_ON_BAT = "powersave";

      CPU_BOOST_ON_AC = 1;
      CPU_BOOST_ON_BAT = 0;

      SOUND_POWER_SAVE_ON_AC = 0;
      SOUND_POWER_SAVE_ON_BAT = 1;

      START_CHARGE_THRESH_BAT0 = 40;
      STOP_CHARGE_THRESH_BAT0 = 80;

      RUNTIME_PM_ON_AC = "on";
      RUNTIME_PM_ON_BAT = "auto";
    };
  };

  # When the Apple Magic Keyboard is plugged in, swap left Alt and Super
  # so it matches macOS muscle memory.
  services.udev.extraRules = ''
    ACTION=="add", SUBSYSTEM=="input", ATTR{name}=="Apple Inc. Magic Keyboard with Touch ID and Numeric Keypad", TAG+="systemd", ENV{SYSTEMD_USER_WANTS}="apple-keyboard-remap.service"
  '';

  systemd.user.services.apple-keyboard-remap = {
    description = "Remap Apple Magic Keyboard layout";
    serviceConfig = {
      Type = "oneshot";
      ExecStart = let
        script = pkgs.writeShellScript "apple-keyboard-remap" ''
          sleep 1
          KB_NAME="Apple Inc. Magic Keyboard with Touch ID and Numeric Keypad"
          KB_ID=$(${pkgs.xorg.xinput}/bin/xinput list --id-only "$KB_NAME" 2>/dev/null || true)
          if [ -n "$KB_ID" ]; then
            ${pkgs.xorg.setxkbmap}/bin/setxkbmap -device "$KB_ID" -layout us -option altwin:swap_lalt_lwin
          fi
        '';
      in "${script}";
    };
    environment = {
      DISPLAY = ":0";
    };
  };

  services.xserver = {
    dpi = 160;

    displayManager.sessionCommands = ''
      # Remap Apple keyboard on login if already plugged in
      KB_NAME="Apple Inc. Magic Keyboard with Touch ID and Numeric Keypad"
      KB_ID=$(xinput list --id-only "$KB_NAME" 2>/dev/null || true)

      if [ -n "$KB_ID" ]; then
        setxkbmap -device "$KB_ID" -layout us -option altwin:swap_lalt_lwin
      fi
    '';
  };

  environment.systemPackages = with pkgs; [
    blueman
    google-chrome
    spotify
    slack
    zoom-us
  ];
  environment.variables.BROWSER = "google-chrome";
}
