# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
      ../hosts/configuration.nix 
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/db2170a7-c6a2-4169-8e36-8bf794cbb49b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-f262b404-e34e-4a98-8965-0b5f80c3240c".device = "/dev/disk/by-uuid/f262b404-e34e-4a98-8965-0b5f80c3240c";
  boot.initrd.luks.devices."luks-3292d5bb-e0c1-4862-aedc-7589dd5022f2".device = "/dev/disk/by-uuid/3292d5bb-e0c1-4862-aedc-7589dd5022f2";
  
  # This disables power saving for the wifi driver.
  # When this is enabled it intermittently drops out.
  boot.extraModprobeConfig = ''
  options mt7921e power_save=0
'';

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/000E-AB73";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/3e1b5652-e8b7-41a6-9b43-3c0a6007931f"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp192s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  nixpkgs.overlays = [
    (import ../overlays/google-chrome.nix)
  ];

  services.logind.lidSwitch = "suspend";
  services.xserver.dpi = 160;

  powerManagement.powertop.enable = true;
  services.tlp = {
    enable = true;
    settings = {
      # CPU scaling for AMD
      CPU_SCALING_GOVERNOR_ON_AC = "performance";
      CPU_SCALING_GOVERNOR_ON_BAT = "powersave";
      
      # AMD CPU boost
      CPU_BOOST_ON_AC = 1;
      CPU_BOOST_ON_BAT = 0;
      
      # Enable audio power saving
      SOUND_POWER_SAVE_ON_AC = 0;
      SOUND_POWER_SAVE_ON_BAT = 1;
      
      # Battery charge thresholds (if your laptop supports it)
      START_CHARGE_THRESH_BAT0 = 40;
      STOP_CHARGE_THRESH_BAT0 = 80;
      
      # Runtime power management for PCI(e) devices
      RUNTIME_PM_ON_AC = "on";
      RUNTIME_PM_ON_BAT = "auto";
    };
  };

  environment.systemPackages = with pkgs; [
    blueman
    google-chrome
    spotify
    slack
    zoom-us
  ];
  environment.variables.BROWSER = "google-chrome";
}
